export const BUSINESS_PRICING_PLANS = [
  {
    name: "Free User",
    planCode: "FREE_USER",
    price: "0",
    priceDisplay: "R0 / $0",
    priceCurrency: "ZAR",
    billingSuffix: null,
    caption: "Free user",
    highlight: false,
    registrationPrivilege: "USER",
    registrationService: "FREE_USER_ACCESS",
    description: "For customers using tickets, job applications, cart checkout, profile access, and QR purchase records.",
    features: ["Free user account", "Public job board", "Job applications", "QR ticket access", "Cart checkout", "Profile dashboard"],
  },
  {
    name: "Free Affiliate",
    planCode: "FREE_AFFILIATE",
    price: "0",
    priceDisplay: "R0 / $0",
    priceCurrency: "ZAR",
    billingSuffix: null,
    caption: "Free affiliate",
    highlight: false,
    registrationPrivilege: "AFFILIATE",
    registrationService: "FREE_AFFILIATE_ACCESS",
    description: "For affiliate users who need referral links, QR promotion assets, campaign workspace, and dashboard visibility.",
    features: ["Free affiliate account", "Referral link shell", "QR promotion cards", "Campaign assets", "Commission visibility", "Affiliate dashboard"],
  },
  {
    name: "Free Trial Business",
    planCode: "FREE_TRIAL_BUSINESS",
    price: "0",
    priceDisplay: "R0 / $0",
    priceCurrency: "ZAR",
    billingSuffix: "14 days",
    caption: "King-Sparkon-Strengths trial",
    highlight: false,
    registrationPrivilege: "BUSINESS_OWNER",
    registrationService: "FULL_BUSINESS_SUITE",
    description: "For business owners testing the King Sparkon platform and requesting a free Dev Hub quote before a paid Plus or Pro plan.",
    features: ["14-day business free trial", "King-Sparkon-Strengths free quote", "Dev Hub discovery", "2 workers", "Unlimited products", "Core owner dashboard"],
  },
  {
    name: "Plus",
    planCode: "PLUS",
    price: "880.00",
    priceDisplay: "R880 / $49",
    priceCurrency: "ZAR",
    billingSuffix: "month",
    caption: "Growth business",
    highlight: true,
    registrationPrivilege: "BUSINESS_OWNER",
    registrationService: "FULL_BUSINESS_SUITE",
    description: "For growing businesses that need workers, product scanning, cart visibility, QR tickets, jobs, promotions, reports, and Dev Hub strength.",
    features: ["14-day business trial included", "Product and barcode scanning", "Cart and transactions", "QR tickets and capacity", "Jobs and applications", "King-Sparkon-Strengths free quote"],
  },
  {
    name: "Pro",
    planCode: "PRO",
    price: "2300.00",
    priceDisplay: "R2,300 / $129",
    priceCurrency: "ZAR",
    billingSuffix: "month",
    caption: "King operations",
    highlight: false,
    registrationPrivilege: "BUSINESS_OWNER",
    registrationService: "FULL_BUSINESS_SUITE",
    description: "For serious operators who need unlimited workers, tips, reporting, audit history, full platform control, and Dev Hub implementation support.",
    features: ["14-day business trial included", "Unlimited workers", "Worker tips", "Advanced reports", "QA and maintenance support", "Cloud implementation support"],
  },
] as const;

export const SOFTWARE_APPLICATION_OFFERS = BUSINESS_PRICING_PLANS.map(({ name, price, priceCurrency }) => ({
  "@type": "Offer",
  name,
  price,
  priceCurrency,
}));

export const AFFILIATE_COMMISSION_TIERS = [
  { rate: 18, label: "first 3 months" },
  { rate: 23, label: "after 3 months" },
  { rate: 28, label: "after 1 year" },
] as const;

export const AFFILIATE_COMMISSION_SUMMARY = AFFILIATE_COMMISSION_TIERS.map((tier) => `${tier.rate}% ${tier.label}`).join(", ");
